apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tehilaNi/gitops-webapp.git 
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated: null
